var quotesList = [
  "Whenever dharma declines and the purpose of life is forgotten, I manifest myself on earth. I am born in every age to protect the good, to destroy evil, and to reestablish dharma.",
  "As they approach me, so I receive them. All paths, Arjuna, lead to me.",
  "I am the beginning, middle, and end of creation.",
  "Among animals I am the lion; among birds, the eagle Garuda. I am Prahlada, born among the demons, and of all that measures, I am time.",
  "I am death, which overcomes all, and the source of all beings still to be born.",
  "Just remember that I am, and that I support the entire cosmos with only a fragment of my being.",
  "Behold, Arjuna, a million divine forms, with an infinite variety of color and shape. Behold the gods of the natural world, and many more wonders never revealed before. Behold the entire cosmos turning within my body, and the other things you desire to see.",
  "I am time, the destroyer of all; I have come to consume the world.",
  "That one is dear to me who runs not after the pleasant or away from the painful, grieves not, lusts not, but lets things come and go as they happen.",
  "Just as a reservoir is of little use when the whole countryside is flooded, scriptures are of little use to the illumined man or woman, who sees the Lord everywhere.",
  "They alone see truly who see the Lord the same in every creature, who see the deathless in the hearts of all that die. Seeing the same Lord everywhere, they do not harm themselves or others. Thus they attain the supreme goal.",
  "With a drop of my energy I enter the earth and support all creatures. Through the moon, the vessel of life-giving fluid, I nourish all plants. I enter breathing creatures and dwell within as the life-giving breath. I am the fire in the stomach which digests all food.",
  "There are three gates to this self-destructive hell: lust, anger, and greed. Renounce these three.",
  "Pleasure from the senses seems like nectar at first, but it is bitter as poison in the end.",
  "That which seems like poison at first, but tastes like nectar in the end - this is the joy of sattva, born of a mind at peace with itself.",
  "The Lord dwells in the hearts of all creatures and whirls them round upon the wheel of maya. Run to him for refuge with all your strength, and peace profound will be yours through his grace.",
  "Whatever you do, make it an offering to me - the food you eat, the sacrifices you make, the help you give, even your suffering.",
  "I am heat; I give and withhold the rain. I am immortality and I am death; I am what is and what is not.",
  "Those who worship other gods with faith and devotion also worship me, Arjuna, even if they do not observe the usual forms. I am the object of all worship, its enjoyer and Lord.",
  "Those who remember me at the time of death will come to me. Do not doubt this. Whatever occupies the mind at the time of death determines the destination of the dying; always they will tend toward that state of being.",
  "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.",
  "They are forever free who renounce all selfish desires and break away from the egocage of 'I', 'me', and 'mine' to be united with the Lord. This is the supreme state. Attain to this, and pass from death to immortality.",
  "They live in wisdom who see themselves in all and all in them, who have renounced every selfish desire and sense-craving tormenting the heart.",
  "The meaning of Karma is in the intention. The intention behind action is what matters. Those who are motivated only by desire for the fruits of action are miserable, for they are constantly anxious about the results of what they do.",
  "You have the right to work, but never to the fruit of work. You should never engage in action for the sake of reward, nor should you long for inaction.",
  "Perform work in this world, Arjuna, as a man established within himself - without selfish attachments, and alike in success and defeat. For yoga is perfect evenness of mind.",
  "At the beginning of time I declared two paths for the pure heart: jnana yoga, the contemplative path of spiritual wisdom, and karma yoga, the active path of selfless service. There are the fundamental different types of yoga.",
  "Do your work with the welfare of others always in mind. It was by such work that Janaka attained perfection; others too have followed this path.",
  "There is nothing in the three worlds for me to gain, Arjuna, nor is there anything I do not have; I continue to act, but I am not driven by any need of my own.",
  "The ignorant work for their own profit, Arjuna; the wise work for the welfare of the world, without thought for themselves.",
  "It is better to strive in one's own dharma than to succeed in the dharma of another. Nothing is ever lost in following one's own dharma, but competition in another's dharma breeds fear and insecurity.",
  "The senses are higher than the body, the mind higher than the senses; above the mind is the intellect, and above the intellect is the Atman. Thus, knowing that which is supreme, let the Atman rule the ego. Use your mighty arms to slay the fierce enemy that is selfish desire.",
  "You and I have passed through many births, Arjuna. You have forgotten, but I remember them all.",
  "My true being is unborn and changeless. I am the Lord who dwells in every creature. Through the power of my own maya, I manifest myself in a finite form.",
  "Those who know me as their own divine Self break through the belief that they are the body and are not reborn as separate creatures. Such a one, Arjuna, is united with me.",
  "Delivered from selfish attachment, fear, and anger, filled with me, surrendering themselves to me, purified in the fire of my being, many have reached the state of unity in me.",
  "Actions do not cling to me because I am not attached to their results. Those who understand this and practice it live in freedom.",
  "The wise see that there is action in the midst of inaction and inaction in the midst of action. Their consciousness is unified, and every act is done with complete awareness.",
  "The process of offering is Brahman; that which is offered is Brahman. Brahman offers the sacrifice in the fire of Brahman. Brahman is attained by those who see Brahman in every action.",
  "The offering of wisdom is better than any material offering, Arjuna; for the goal of all work is spiritual wisdom.",
  "Approach those who have realized the purpose of life and question them with reverence and devotion; they will instruct you in this wisdom.",
  "Even if you were the most sinful of sinners, Arjuna, you could cross beyond all sin by the raft of spiritual wisdom.",
  "Krishna delivers the Gita to Arjuna.",
  "As the heat of a fire reduces wood to ashes, the fire of knowledge burns to ashes all karma.",
  "Those who surrender to Brahman all selfish attachments are like the leaf of a lotus floating clean and dry in water. Sin cannot touch them.",
  "Those who renounce attachment in all their deeds live content in the 'city of nine gates', the body, as its master. They are not driven to act, nor do they involve others in action.",
  "Those who possess this wisdom have equal regard for all. They see the same Self in a spiritual aspirant and an outcaste, in an elephant, a cow, and a dog.",
  "Pleasures conceived in the world of the senses have a beginning and an end and give birth to misery, Arjuna. The wise do not look for happiness in them. But those who overcome the impulses of lust and anger which arise in the body are made whole and live in joy. They find their joy, their rest, and their light completely within themselves. United with the Lord, they attain nirvana in Brahman.",
  "Free from anger and selfish desire, unified in mind, those who follow the path of yoga and realize the Self are established forever in that supreme state.",
  "Knowing me as the friend of all creatures, the Lord of the universe, the end of all offerings and all spiritual disciplines, they attain eternal peace.",
  "It is not those who lack energy or refrain from action, but those who work without expectation of reward who attain the goal of meditation.",
  "Those who cannot renounce attachment to the results of their work are far from the path.",
  "Reshape yourself through the power of your will; never let yourself be degraded by self-will. The will is the only friend of the Self, and the will is the only enemy of the Self.",
  "To those who have conquered themselves, the will is a friend. But it is the enemy of those who have not found the Self within them.",
  "The supreme Reality stands revealed in the consciousness of those who have conquered themselves. They live in peace, alike in cold and heat, pleasure and pain, praise and blame.",
  "With all fears dissolved in the peace of the Self and all actions dedicated to Brahman, controlling the mind and fixing it on me, sit in meditation with me as your only goal.",
  "Arjuna, those who eat too much or eat too little, who sleep too much or sleep too little, will not succeed in meditation. But those who are temperate in eating and sleeping, work and recreation, will come to the end of sorrow through meditation.",
  "In the still mind, in the depths of meditation, the Self reveals itself. Beholding the Self by means of the Self, an aspirant knows the joy and peace of complete fulfillment.",
  "Wherever the mind wanders, restless and diffuse in its search for satisfaction without, lead it within; train it to rest in the Self.",
  "I am ever present to those who have realized me in every creature. Seeing all life as my manifestation, they are never separated from me.",
  "When a person responds to the joys and sorrows of others as if they were his own, he has attained the highest state of spiritual union.",
  "No one who does good work will ever come to a bad end, either here or in the world to come.",
  "Through constant effort over many lifetimes, a person becomes purified of all selfish desires and attains the supreme goal of life.",
  "Meditation is superior to severe asceticism and the path of knowledge. It is also superior to selfless service. May you attain the goal of meditation, Arjuna!",
  "Even among those who meditate, that man or woman who worships me with perfect faith, completely absorbed in me, is the most firmly established in yoga.",
  "With your mind intent on me, Arjuna, discipline yourself with the practice of yoga. Depend on me completely. Listen, and I will dispel all your doubts; you will come to know me fully and be united with me.",
  "The birth and dissolution of the cosmos itself take place in me. There is nothing that exists separate from me, Arjuna. The entire universe is suspended from me as my necklace of jewels.",
  "Arjuna, I am the taste of pure water and the radiance of the sun and moon. I am the sacred word and the sound heard in air, and the courage of human beings. I am the sweet fragrance in the earth and the radiance of fire; I am the life in every creature and the striving of the spiritual aspirant.",
  "My eternal seed, Arjuna, is to be found in every creature. I am the power of discrimination in those who are intelligent, and the glory of the noble. In those who are strong, I am strength, free from passion and selfish attachment. I am desire itself, if that desire is in harmony with the purpose of life.",
  "The states of sattva, rajas, and tamas come from me, but I am not in them.",
  "The three gunas make up my divine maya, difficult to overcome. But they cross over this maya who take refuge in me.",
  "Some come to the spiritual life because of suffering, some in order to understand life; some come through a desire to achieve life's purpose, and some come who are men and women of wisdom. Unwavering in devotion, always united with me, the man or woman of wisdom surpasses all the others.",
  "After many births the wise seek refuge in me, seeing me everywhere and in everything. Such great souls are very rare.",
  "The world, deluded, does not know that I am without birth and changeless. I know everything about the past, the present, and the future, Arjuna; but there is no one who knows me completely.",
  "Delusion arises from the duality of attraction and aversion, Arjuna; every creature is deluded by these from birth.",
  "Those who see me ruling the cosmos, who see me in the adhibhuta, the adhidaiva, and the adhiyajna, are conscious of me even at the time of death.",
  "The Lord is the supreme poet, the first cause, the sovereign ruler, subtler than the tiniest particle, the support of all, inconceivable, bright as the sun, beyond darkness.",
  "Remembering me at the time of death, close down the doors of the senses and place the mind in the heart. Then, while absorbed in meditation, focus all energy upwards to the head. Repeating in this state the divine name, the syllable Om that represents the changeless Brahman, you will go forth from the body and attain the supreme goal.",
  "I am easily attained by the person who always remembers me and is attached to nothing else. Such a person is a true yogi, Arjuna.",
  "Every creature in the universe is subject to rebirth, Arjuna, except the one who is united with me.",
  "The six months of the northern path of the sun, the path of light, of fire, of day, of the bright fortnight, leads knowers of Brahman to the supreme goal. The six months of the southern path of the sun, the path of smoke, of night, of the dark fortnight, leads other souls to the light of the moon and to rebirth.",
  "Under my watchful eye the laws of nature take their course. Thus is the world set in motion; thus the animate and the inanimate are created.",
  "I am the ritual and the sacrifice; I am true medicine and the mantram. I am the offering and the fire which consumes it, and the one to whom it is offered.",
  "I am the father and mother of this universe, and its grandfather too; I am its entire support. I am the sum of all knowledge, the purifier, the syllable Om; I am the sacred scriptures, the Rig, Yajur, and Sama Vedas.",
  "I am the goal of life, the Lord and support of all, the inner witness, the abode of all. I am the only refuge, the one true friend; I am the beginning, the staying, and the end of creation; I am the womb and the eternal seed.",
  "Those who follow the rituals given in the Vedas, who offer sacrifices and take soma, free themselves from evil and attain the vast heaven of the gods, where they enjoy celestial pleasures. When they have enjoyed these fully, their merit is exhausted and they return to this land of death. Thus observing Vedic rituals but caught in an endless chain of desires, they come and go.",
  "Those who worship me and meditate on me constantly, without any other thought - I will provide for all their needs.",
  "Those who worship the devas will go to the realm of the devas; those who worship their ancestors will be united with them after death. Those who worship phantoms will become phantoms; but my devotees will come to me. Those who worship the devas will go to the realm of the devas; those who worship their ancestors will be united with them after death. Those who worship phantoms will become phantoms; but my devotees will come to me.",
  "Fill your mind with me; love me; serve me; worship me always. Seeking me in your heart, you will at last be united with me.",
  "All the scriptures lead to me; I am their author and their wisdom.",
  "Bhishma, Drona, Jayadratha, Karna, and many others are already slain. Kill those whom I have killed. Do not hesitate. Fight in this battle and you will conquer your enemies.",
  "Not by knowledge of the Vedas, nor sacrifice, nor charity, nor rituals, nor even by severe asceticism has any other mortal seen what you have seen, O heroic Arjuna.",
  "Better indeed is knowledge than mechanical practice. Better than knowledge is meditation. But better still is surrender of attachment to results, because there follows immediate peace.",
  "Some realize the Self within them through the practice of meditation, some by the path of wisdom, and others by selfless service. Others may not know these paths; but hearing and following the instructions of an illumined teacher, they too go beyond death.",
  "The brightness of the sun, which lights up the world, the brightness of the moon and of fire - these are my glory.",
  "Calmness, gentleness, silence, self-restraint, and purity: these are the disciplines of the mind.",
  "To refrain from selfish acts is one kind of renunciation, called sannyasa; to renounce the fruit of action is another, called tyaga.",
  "By serving me with steadfast love, a man or woman goes beyond the gunas. Such a one is fit for union with Brahman.",
  "When they see the variety of creation rooted in that unity and growing out of it, they attain fulfillment in Brahman.",
  "I have shared this profound truth with you, Arjuna. Those who understand it will attain wisdom; they will have done that which has to be done.",
  "I give you these precious words of wisdom; reflect on them and then do as you choose."
];

var quotesListHindi = [
  "जब भी धर्म का ह्रास होता है और जीवन का उद्देश्य भूल जाता है, तो मैं स्वयं को पृथ्वी पर प्रकट करता हूं। मैं हर युग में अच्छाई की रक्षा, बुराई को नष्ट करने और धर्म की स्थापना के लिए पैदा हुआ हूं।",
  "जैसे इसी जन्म में जीवात्मा बाल, युवा और वृद्ध शरीर को प्राप्त करती है।वैसे ही जीवात्मा मरने के बाद भी नया शरीर प्राप्त करती है।,इसलिए वीर पुरुष को मृत्यु से घबराना नहीं चाहिए।",
  "न यह शरीर तुम्हारा है, न तुम शरीर के हो।यह अग्नि, जल, वायु, पृथ्वी, आकाश से मिलकर बना है और इसी में मिल जायेगा।,परन्तु आत्मा स्थिर है – फिर तुम क्या हो?",
  "आत्मा अजर अमर है। जो लोग इस आत्मा को मारने वाला या मरने वाला मानते हैं,वे दोनों ही नासमझ हैं आत्मा ना किसी को मारती है और ना ही किसी के द्वारा मारी जा सकती है।",
  "आत्मा ना कभी जन्म लेती है और ना मरती ही है।,शरीर का नाश होने पर भी इसका नाश नहीं होता।",
  "तुम अपने आपको भगवान को अर्पित करो।,यही सबसे उत्तम सहारा है जो इसके सहारे को जानता है वह भय, चिन्ता, शोक से सर्वदा मुक्त रहता है।",
  "जैसे मनुष्य अपने पुराने वस्त्रों को उतारकर दूसरे नए वस्त्र धारण करता है,वैसे ही जीव मृत्यु के बाद अपने पुराने शरीर को त्यागकर नया शरीर प्राप्त करता है।",
  "शस्त्र इस आत्मा को काट नहीं सकते,अग्नि इसको जला नहीं सकती,जल इसको गीला नहीं कर सकता,और वायु इसे सुखा नहीं सकती।",
  "परिवर्तन संसार का नियम है।,जिसे तुम मृत्यु समझते हो, वही तो जीवन है।,एक क्षण में तुम करोड़ों के स्वामी बन जाते हो,दूसरे ही क्षण में तुम दरिद्र हो जाते हो।,मेरा-तेरा, छोटा-बड़ा, अपना-पराया, मन से मिटा दो, फिर सब तुम्हारा है, तुम सबके हो।",
  "हे अर्जुन!,सभी प्राणी जन्म से पहले अप्रकट थे और मृत्यु के बाद फिर अप्रकट हो जायेंगे।,केवल जन्म और मृत्यु के बीच प्रकट दिखते हैं, फिर इसमें शोक करने की क्या बात है?",
  "सम्मानित व्यक्ति के लिए अपमान मृत्यु से भी बढ़कर है।",
  "जो हुआ, वह अच्छा हुआ,जो हो रहा है, वह अच्छा हो रहा है,जो होगा, वह भी अच्छा ही होगा,तुम भूत का पश्चाताप न करो।,भविष्य की चिन्ता न करो। वर्तमान चल रहा है।",
  "क्रोध से भ्रम पैदा होता है. भ्रम से बुद्धि व्यग्र होती है। जब बुद्धि व्यग्र होती है तब तर्क नष्ट हो जाता है। जब तर्क नष्ट होता है तब व्यक्ति का पतन हो जाता है",
  "सुख – दुःख, लाभ – हानि और जीत – हार की चिंता ना करके,मनुष्य को अपनी शक्ति के अनुसार कर्तव्य - कर्म करना चाहिए।ऐसे भाव से कर्म करने पर मनुष्य को पाप नहीं लगता।",
  "खाली हाथ आये और खाली हाथ वापस चले।,जो आज तुम्हारा है, कल और किसी का था, परसों किसी और का होगा,तुम इसे अपना समझ कर मग्न हो रहे हो।,बस यही प्रसन्नता तुम्हारे दु:खों का कारण है।",
  "जो मन को नियंत्रित नहीं करते उनके लिए वह शत्रु के समान कार्य करता है।",
  "तुम्हारा क्या गया, जो तुम रोते हो?,तुम क्या लाए थे, जो तुमने खो दिया?तुमने क्या पैदा किया था, जो नाश हो गया?न तुम कुछ लेकर आये, जो लिया यहीं से लिया।,जो दिया, यहीं पर दिया।,जो लिया, इसी (भगवान) से लिया।,जो दिया, इसी को दिया।",
  "अगर आप अपने लक्ष्‍य को प्राप्‍त करने में असफल हो जाते हैं,तो अपनी रणनीति बदलिए, न कि लक्ष्‍य।",
  "क्रोध से भ्रम पैदा होता है भ्रम से बुद्धि व्यग्र होती है जब बुद्धि व्यग्र होती है तब तर्क नष्ट हो जाता है जब तर्क नष्ट होता हैतब व्यक्ति का पतन हो जाता है.",
  "ऐसा कोई नहीं, जिसने भी इस संसार मे अच्छा कर्म किया हो और उसका बुरा अंत हुआ हो, चाहे इस काल में हो या आने वाले काल में।",
  "फल की अभिलाषा छोड़ कर,कर्म करने वाला पुरूष ही अपने जीवन को सफल बनाता है।",
  "मन अशांत है और उसे नियंत्रित करना कठिन है, लेकिन अभ्यास से इसे वश में किया जा सकता है।",
  "अपने कर्म पर अपना दिल लगाएं, न की उसके फल पर।",
  "वह जो मृत्यु के समय मुझे स्मरण करते हुए अपना शरीर त्यागता है, वह मेरे धाम को प्राप्त होता है - इसमें कोई संशय नहीं है।",
  "किसी दूसरे के जीवन के साथ,पूर्ण रूप से जीने से अच्छा है,कि हम अपने स्वंय के भाग्य के अनुसार अपूर्ण जियें।",
  "जो मन को नियंत्रित नहीं करते,\bउनके लिए वह शत्रु के समान कार्य करता है।",
  "एक उपहार तभी अच्छा और पवित्र लगता है,\bजब वह दिल से किसी सही व्यक्ति को सही समय और सही जगह पर दिया जाये,और जब उपहार देने वाला व्यक्ति का दिल उस उपहार के बदले,कुच्छ पाने की उम्मीद ना रखता हो।",
  "आत्म-ज्ञान की तलवार से काटकर,अपने ह्रदय से अज्ञान के संदेह को अलग कर दो, अनुशाषित रहो, उठो।",
  "मनुष्य अपने विश्वास से निर्मित होता है,जैसा वो विश्वास करता है वैसा वो बन जाता है।",
  "जो कोई भी जिस किसी भी देवता की पूजा,विश्वास के साथ करने की इच्छा रखता है,मैं उसका विश्वास उसी देवता में दृढ कर देता हूँ।",
  "नर्क के तीन द्वार हैं:1. वासना2. क्रोध 3. लालच।",
  "लोग आपके अपमान के बारे में हमेशा बात करेंगे, सम्मानित व्यक्ति के लिए अपमान मृत्यु से भी बदतर है।",
  "हम जो देखते हैं वो हम हैं,और हम जो हैं हम उसी वस्तु को निहारते हैं,इसलिए जीवन मे हमेशा अच्छी और सकारत्मक चीज़ो को देखें और सोचें।",
  "केवल मन ही,किसी का मित्र और शत्रु होता है।",
  "जो चीज हमारे हाथ में नहीं है,उसके विषय में चिंता करके कोई फायदा नहीं।",
  "हे अर्जुन!जब जब संसार में धर्म की हानि और अधर्म की वृद्धि होती है,तब – तब अच्छे लोगों की रक्षा, दुष्टों का संहार, और धर्म की स्थापना करने के लिए,मैं हर युग में अवतरित होता हूँ|",
  "श्रेष्ठ मनुष्य जैसा आचरण करता है,दूसरे लोग भी वैसा ही आचरण करते हैं।,वह जो प्रमाण देता है,जनसमुदाय उसी का अनुसरण करता है।",
  "दुःख से जिसका मन परेशान नहीं होता,सुख की जिसको आकांक्षा नहीं होती,तथा जिसके मन में राग, भय और क्रोध नष्ट हो गए हैं,ऐसा मुनि आत्मज्ञानी कहलाता है।",
  "जो ज्ञान और कर्म को एक रूप में देखता है,वही सही मायने में देखता है.",
  "हर व्यक्ति का विश्वास उसकी प्रकृति के अनुसार होता है।",
  "हे अर्जुन!,हम दोनों ने कई जन्म लिए हैं। मुझे याद हैं,लेकिन तुम्हें नहीं।",
  "मन की गतिविधियों, होश, श्वास, और भावनाओं के माध्यम से भगवान की शक्ति सदा तुम्हारे साथ है,और लगातार तुम्हें बस एक साधन की तरह प्रयोग कर के सभी कार्य कर रही है।",
  "जो हमेशा मेरा स्मरण या एक-चित्त मन से मेरा पूजन करते हैं,मैं व्यक्तिगत रूप से उनके कल्याण का उत्तरदायित्व लेता हूँ।",
  "कर्म योग वास्तव में एक परम रहस्य है।",
  "इंद्रियों की दुनिया में कल्पना सुखों की शुरुआत है,और अंत भी, जो दुख को जन्म देता है।",
  "बुद्धिमान व्यक्ति को समाज कल्याण के लिए बिना आसक्ति के काम करना चाहिए।",
  "जो व्यक्ति आध्यात्मिक जागरूकता के शिखर तक पहुँच चुके हैं,उनका मार्ग है निःस्वार्थ कर्म. जो भगवान् के साथ संयोजित हो चुके हैं उनका मार्ग है स्थिरता और शांति।",
  "यद्यपि मैं इस तंत्र का रचयिता हूँ,लेकिन सभी को यह ज्ञात होना चाहिए कि मैं कुछ नहीं करता और मैं अनंत हूँ।",
  "जब वे अपने कार्य में आनंद खोज लेते हैं तब वे पूर्णता प्राप्त करते हैं।",
  "वह जो सभी इच्छाएं त्याग देता है,मैं और मेरा की लालसा और भावना से मुक्त हो जाता है उसे शांति प्राप्त होती है।",
  "मेरे लिए ना कोई घृणित है ना प्रिय,किन्तु जो व्यक्ति भक्ति के साथ मेरी पूजा करते हैं,वो मेरे साथ हैं और मैं भी उनके साथ हूँ।",
  "जो इस लोक में अपने काम की सफलता की कामना रखते हैं,वे देवताओं का पूजन करें।",
  "मैं ऊष्मा देता हूँ,मैं वर्षा करता हूँ,मैं वर्षा रोकता भी हूँ,मैं अमरत्व भी हूँ,और मृत्यु भी मैं ही हूँ।",
  "बुरे कर्म करने वाले,सबसे नीच व्यक्ति जो राक्षसी प्रवित्तियों से जुड़े हुए हैं,और जिनकी बुद्धि माया ने हर ली है,वो मेरी पूजा या मुझे पाने का प्रयास नहीं करते।",
  "वह जो इस ज्ञान में विश्वास नहीं रखते,मुझे प्राप्त किये बिना जन्म और मृत्यु के चक्र का अनुगमन करते हैं",
  "हे अर्जुन!मैं भूत, वर्तमान और भविष्य के सभी प्राणियों को जानता हूँ,किन्तु वास्तविकता में कोई मुझे नहीं जानता।",
  "स्वर्ग प्राप्त करने और वहां कई वर्षों तक वास करने के पश्चात,एक असफल योगी का पुन: एक पवित्र और समृद्ध कुटुंब में जन्म होता है।",
  "निर्माण केवल पहले से मौजूद चीजों का प्रक्षेपण है।",
  "मैं सभी प्राणियों के ह्रदय में विद्यमान हूँ।",
  "ऐसा कुछ भी नहीं, चेतन या अचेतन,जो मेरे बिना अस्तित्व मे हो सकता हो।",
  "स्वार्थ से भरा कार्य इस दुनिया को क़ैद मे रख देगा,अपने जीवन में स्वार्थ को दूर रखे,बिना किसी व्यक्तिगत लाभ के।",
  "अपने अनिवार्य कार्य करो,क्योंकि वास्तव में कार्य करना,निष्क्रियता से बेहतर है।",
  "इस जीवन में ना कुछ खोता है ना व्यर्थ होता है।",
  "जन्म लेने वाले के लिए मृत्यु उतनी ही निश्चित है,जितना कि मृत होने वाले के लिए जन्म लेना,इसलिए जो अपरिहार्य है उस पर शोक मत करो।",
  "भगवान या परमात्मा की शांति उनके साथ होती है,जिसके मन और आत्मा में एकता हो,जो इच्छा और क्रोध से मुक्त हो,जो अपने खुद की आत्मा को सही मायने में जानता हो।",
  "सभी अच्छे काम छोड़ कर बस भगवान में पूर्ण रूप से समर्पित हो जाओ,मैं तुम्हे सभी पापों से मुक्त कर दूंगा, शोक मत करो।",
  "किसी और का काम पूर्णता से करने से कहीं अच्छा है कि अपना काम करें,भले ही उसे अपूर्णता से करना पड़े।",
  "प्रबुद्ध व्यक्ति के लिए,गंदगी का ढेर, पत्थर, और सोना,सभी समान हैं।",
  "मैं सभी प्राणियों को सामान रूप से देखता हूँ,ना कोई मुझे कम प्रिय है ना अधिक,लेकिन जो मेरी प्रेमपूर्वक आराधना करते हैं,वो मेरे भीतर रहते हैं और मैं उनके जीवन में आता हूँ।",
  "प्रबुद्ध व्यक्ति सिवाय ईश्वर के,किसी और पर निर्भर नहीं करता।",
  "सन्निहित आत्मा का अस्तित्व अविनाशी और अनन्त हैं, केवल भौतिक शरीर तथ्यात्मक रूप से खराब है,इसलिए हे अर्जुन! लड़ते रहो।",
  "हे अर्जुन!केवल भाग्यशाली योद्धा ही ऐसा युद्ध लड़ने का अवसर पाते हैं जो स्वर्ग के द्वार के सामान है।",
  "भगवान प्रत्येक वस्तु में है और सबके ऊपर भी।",
  "सदैव संदेह करने वाले व्यक्ति के लिए प्रसन्नता ना इस लोक में है ना ही कहीं और।",
  "आपके सर्वलौकिक रूप का मुझे न प्रारंभ न मध्य न अंत दिखाई दे रहा है।",
  "सभी कार्य ध्यान से करो,करुणा द्वारा निर्देशित किए हुये।",
  "तुम उसके लिए शोक करते हो जो शोक करने के योग्य नहीं हैं,और फिर भी ज्ञान की बातें करते हो,बुद्धिमान व्यक्ति ना जीवित और ना ही मृत व्यक्ति के लिए शोक करते हैं।",
  "कभी ऐसा समय नहीं था जब मैं, तुम,या ये राजा-महाराजा अस्तित्व में नहीं थे,ना ही भविष्य में कभी ऐसा होगा कि हमारा अस्तित्व समाप्त हो जाये।",
  "कर्म मुझे बांधता नहीं,क्योंकि मुझे कर्म के प्रतिफल की कोई इच्छा नहीं।",
  "उससे मत डरो जो वास्तविक नहीं है,क्योंकि वह ना कभी था ना कभी होगा,जो वास्तविक है वो हमेशा था और उसे कभी नष्ट नहीं किया जा सकता।",
  "अप्राकृतिक कर्म बहुत तनाव पैदा करता है।",
  "मैं उन्हें ज्ञान देता हूँ जो सदा मुझसे जुड़े रहते हैं और जो मुझसे प्रेम करते हैं।",
  "मेरी कृपा से कोई सभी कर्तव्यों का निर्वाह करते हुए भी,बस मेरी शरण में आकर अनंत अविनाशी निवास को प्राप्त करता है।",
  "बुद्धिमान व्यक्ति कामुक सुख में आनंद नहीं लेता।",
  "मैं धरती की मधुर सुगंध हूँ, मैं अग्नि की ऊष्मा हूँ,सभी जीवित प्राणियों का जीवन और सन्यासियों का आत्मसंयम हूँ।",
  "वह जो वास्तविकता में मेरे उत्कृष्ट जन्म और गतिविधियों को समझता है,वह शरीर त्यागने के बाद पुनः जन्म नहीं लेता और मेरे धाम को प्राप्त होता है।",
  "कर्म उसे नहीं बांधता जिसने काम का त्याग कर दिया है।",
  "मैं समय हूँ, सबका नाशक,मैं आया हूँ दुनिया का उपभोग करने के लिए।",
  "व्यक्ति जो चाहे बन सकता है,यदि वह विश्वास के साथ इच्छित वस्तु पर लगातार चिंतन करे।",
  "यह बड़े ही शोक की बात है,कि हम लोग बड़ा भारी पाप करने का निश्चय कर बैठते हैं,तथा राज्य और सुख के लोभ से अपने स्वजनों का नाश करने को तैयार हैं।",
  "हे अर्जुन! विषम परिस्थितियों में कायरता को प्राप्त करना,श्रेष्ठ मनुष्यों के आचरण के विपरीत है।,ना तो ये स्वर्ग प्राप्ति का साधन है,और ना ही इससे कीर्ति प्राप्त होगी।",
  "कर्म ही पूजा है।",
  "हे अर्जुन!तुम ज्ञानियों की तरह बात करते हो,लेकिन जिनके लिए शोक नहीं करना चाहिए,उनके लिए शोक करते हो।,मृत या जीवित, ज्ञानी किसी के लिए शोक नहीं करते।",
  "केवल कर्म करना ही मनुष्य के वश में है,कर्मफल नहीं। इसलिए तुम कर्मफल की आशक्ति में ना फंसो तथा अपने कर्म का त्याग भी ना करो",
  "जब तुम्हारी बुद्धि मोहरूपी दलदल को पार कर जाएगी,उस समय तुम शास्त्र से सुने गए और सुनने योग्य वस्तुओं से भी वैराग्य प्राप्त करोगे।",
  "जो भी मनुष्य अपने जीवन अध्यात्मिक ज्ञान के चरणों के लिए दृढ़ संकल्पो में स्थिर हैं,वह समान्य रूप से संकटो के आक्रमण को सहन कर सकते हैं, और निश्चित रूप से खुशियाँ और मुक्ति पाने के पात्र हैं।",
  "हे कुंतीनंदन!,संयम का प्रयत्न करते हुए ज्ञानी मनुष्य के मन को भी चंचल इन्द्रियां बलपूर्वक हर लेती हैं।,जिसकी इन्द्रियां वश में होती हैं,उसकी बुद्धि स्थिर होती है।",
  "विषयों का चिंतन करने से विषयों की आसक्ति होती है।आसक्ति से इच्छा उत्पन्न होती है और इच्छा से क्रोध होता है। क्रोध से सम्मोहन और अविवेक उत्पन्न होता है,सम्मोहन से मन भृष्ट हो जाता है।मन नष्ट होने पर बुद्धि का नाश होता है,और बुद्धि का नाश होने से मनुष्य का पतन होता है।",
  "हर काम का फल मिलता है - 'इस जीवन में ना कुछ खोता है ना व्यर्थ होता है",
  "क्यों व्यर्थ की चिंता करते हो?,किससे व्यर्थ डरते हो?,कौन तुम्हें मार सक्ता है?,आत्मा ना पैदा होती है, न मरती है।",
  "शांति से सभी दुःखों का अंत हो जाता है,और शांतचित्त मनुष्य की बुद्धि शीघ्र ही स्थिर होकर परमात्मा से युक्त हो जाती है।",
  "जो कुछ भी तू करता है,उसे भगवान को अर्पण करता चल।ऐसा करने से सदा जीवन-मुक्ति का आनंद अनुभव करेगा।",
  "जैसे जल में तैरती नाव को तूफान उसे अपने लक्ष्य से दूर ले जाता है,वैसे ही इन्द्रिय सुख मनुष्य को गलत रास्ते की ओर ले जाता है।",
  "जो मनुष्य सब कामनाओं तो त्यागकर,इच्छा रहित, ममता रहित तथा अहंकार रहित होकर विचरण करता है,वही शांति प्राप्त करता है।",
  "मनुष्य कर्म को त्यागकर कर्म के बंधन से मुक्त नहीं होता।केवल कर्म के त्याग मात्र से ही सिद्धि प्राप्त नहीं होती।कोई भी मनुष्य एक क्षण भी बिना कर्म किये नहीं रह सकता।",
  "मन अशांत है और उसे नियंत्रित करना कठिन है, लेकिन अभ्यास से इसे वश में किया जा सकता है।",
  "जो मनुष्य बिना आलोचना किये,श्रद्धापूर्वक मेरे उपदेश का सदा पालन करते हैं,वे कर्मों के बंधन से मुक्त हो जाते हैं।",
  "इन्द्रियां, मन और बुद्धि काम के निवास स्थान कहे जाते हैं।यह काम इन्द्रियां, मन और बुद्धि को अपने वश में करके ज्ञान को ढककर मनुष्य को भटका देता है।",
  "इन्द्रियां शरीर से श्रेष्ठ कही जाती हैं,इन्द्रियों से परे मन है और मन से परे बुद्धि है,और आत्मा बुद्धि से भी अत्यंत श्रेष्ठ है।",
  "अप्राकृतिक कर्म बहुत तनाव पैदा करता है",
  "काम, क्रोध और लोभ,ये जीव को नरक की ओर ले जाने वाले तीन द्वार हैं,इसलिए इन तीनों का त्याग करना चाहिए|",
  "हे अर्जुन!मेरे जन्म और कर्म दिव्य हैं,इसे जो मनुष्य भली भांति जान लेता है,उसका मरने के बाद पुनर्जन्म नहीं होता तथा वह मेरे लोक, परमधाम को प्राप्त होता है।",
  "हे अर्जुन!जो भक्त जिस किसी भी मनोकामना से मेरी पूजा करते हैं,मैं उनकी मनोकामना की पूर्ति करता हूँ।",
  "जो आशा रहित है,जिसके मन और इन्द्रियां वश में हैं,जिसने सब प्रकार के स्वामित्व का परित्याग कर दिया है,ऐसा मनुष्य शरीर से कर्म करते हुए भी पाप को प्राप्त नहीं होता और कर्म बंधन से मुक्त हो जाता है।",
  "अपने आप जो कुछ भी प्राप्त हो,उसमें संतुष्ट रहने वाला, ईर्ष्या से रहित, सफलता और असफलता में समभाव वाला कर्मयोगी कर्म करता हुआ भी कर्म के बन्धनों से नहीं बंधता है।",
  "हे अर्जुन!जैसे प्रज्वलित अग्नि लकड़ी को जला देती है,वैसे ही ज्ञानरूपी अग्नि कर्म के सारे बंधनों को भस्म कर देती है।",
  "हे अर्जुन!तुम सदा मेरा स्मरण करो और अपना कर्तव्य करो।इस तरह मुझमें अर्पण किये मन और बुद्धि से युक्त होकर निःसंदेह तुम मुझको ही प्राप्त होगे|",
  "सभी प्राणी मेरे लिए समान हैं,न मेरा कोई अप्रिय है और न प्रिय,परन्तु जो श्रद्धा और प्रेम से मेरी उपासना करते हैं,वे मेरे समीप रहते हैं और मैं भी उनके निकट रहता हूँ।",
  "यदि कोई बड़े से बड़ा दुराचारी भी अनन्य भक्ति भाव से मुझे भजता है,तो उसे भी साधु ही मानना चाहिए और वह शीघ्र ही धर्मात्मा हो जाता है,तथा परम शांति को प्राप्त होता है।",
  "हे अर्जुन!तुम यह निश्चयपूर्वक सत्य मानो कि मेरे भक्त का कभी भी विनाश या पतन नहीं होता है।",
  "मैं ही सबकी उत्पत्ति का कारण हूँ,और मुझसे ही जगत का होता है।",
  "जो कार्य में निष्क्रियता, और निष्क्रियता में कार्य देखता है, वह एक बुद्धिमान व्यक्ति है।",
];
