-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJOmDznWBKHvMdM2y
skEwpcg3DyC0R60EkqmWbSspK9agCgYIKoZIzj0DAQehRANCAATmhCtHyUHNISgp
wkhK8gM8LYpJLAak4oQSNWqttc8ztwl59Gn1BoKb5lR4qBb/OKuFT/2vxVqWooOz
Id2c/IA6
-----END PRIVATE KEY-----